// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjgPzvWv0i6qgv5xf-eGq_hJH9vNcPrg',
    appId: '1:881662789064:web:1deafe75f2a10a9e1cecfd',
    messagingSenderId: '881662789064',
    projectId: 'yummygo-5cb3c',
    authDomain: 'yummygo-5cb3c.firebaseapp.com',
    storageBucket: 'yummygo-5cb3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWESVXHGsVO5BE5_z69p4ZILuUXXNJXW4',
    appId: '1:881662789064:android:18a98be502eb3aa81cecfd',
    messagingSenderId: '881662789064',
    projectId: 'yummygo-5cb3c',
    storageBucket: 'yummygo-5cb3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4WcJuJ8QPGbdz-X96YYE8-GEjC3SSKyE',
    appId: '1:881662789064:ios:9be781c022b75a931cecfd',
    messagingSenderId: '881662789064',
    projectId: 'yummygo-5cb3c',
    storageBucket: 'yummygo-5cb3c.firebasestorage.app',
    iosBundleId: 'com.example.yummygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4WcJuJ8QPGbdz-X96YYE8-GEjC3SSKyE',
    appId: '1:881662789064:ios:9be781c022b75a931cecfd',
    messagingSenderId: '881662789064',
    projectId: 'yummygo-5cb3c',
    storageBucket: 'yummygo-5cb3c.firebasestorage.app',
    iosBundleId: 'com.example.yummygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIjgPzvWv0i6qgv5xf-eGq_hJH9vNcPrg',
    appId: '1:881662789064:web:03f28cd051bb54131cecfd',
    messagingSenderId: '881662789064',
    projectId: 'yummygo-5cb3c',
    authDomain: 'yummygo-5cb3c.firebaseapp.com',
    storageBucket: 'yummygo-5cb3c.firebasestorage.app',
  );
}
